export type Shortcut = {
  id: string;
  name: string;
  keys: string;
  where?: string;
  description: string;
};

export const SHORTCUTS: Shortcut[] = [
  {
    id: 'palette',
    name: 'Paleta de comandos',
    keys: 'Ctrl+K / Cmd+K',
    where: 'Global',
    description: 'Abrir comandos e acoes rapidas.',
  },
  {
    id: 'search',
    name: 'Buscar',
    keys: 'Ctrl+P / Cmd+P',
    where: 'Global',
    description: 'Alternar a busca global (Ctrl+/ abre direto).',
  },
  {
    id: 'help',
    name: 'Ajuda / Atalhos',
    keys: '?',
    where: 'Global',
    description: 'Abrir a pagina de ajuda e atalhos.',
  },
  {
    id: 'new-note',
    name: 'Nova nota rapida',
    keys: 'Ctrl+N / Cmd+N',
    where: 'Global',
    description: 'Criar nota rapida e abrir no editor.',
  },
  {
    id: 'new-folder',
    name: 'Nova pasta rapida',
    keys: 'Ctrl+Shift+N / Cmd+Shift+N',
    where: 'Global',
    description: 'Criar pasta rapida.',
  },
  {
    id: 'capture',
    name: 'Captura rapida',
    keys: 'Ctrl+Shift+C / Cmd+Shift+C',
    where: 'Global',
    description: 'Abrir a captura rapida.',
  },
  {
    id: 'close-dialog',
    name: 'Fechar modais',
    keys: 'Esc',
    where: 'Global',
    description: 'Fechar busca, palette ou dialogs.',
  },
  {
    id: 'search-nav',
    name: 'Navegar resultados',
    keys: 'Seta Cima / Seta Baixo',
    where: 'Busca',
    description: 'Mover entre resultados.',
  },
  {
    id: 'search-open',
    name: 'Abrir resultado',
    keys: 'Enter',
    where: 'Busca',
    description: 'Abrir o item selecionado.',
  },
  {
    id: 'palette-nav',
    name: 'Navegar comandos',
    keys: 'Seta Cima / Seta Baixo',
    where: 'Paleta',
    description: 'Mover entre comandos.',
  },
  {
    id: 'palette-exec',
    name: 'Executar comando',
    keys: 'Enter',
    where: 'Paleta',
    description: 'Executar o comando selecionado.',
  },
  {
    id: 'editor-undo',
    name: 'Desfazer',
    keys: 'Ctrl+Z / Cmd+Z',
    where: 'Editor',
    description: 'Desfazer a ultima alteracao.',
  },
  {
    id: 'editor-redo',
    name: 'Refazer',
    keys: 'Ctrl+Y ou Ctrl+Shift+Z',
    where: 'Editor',
    description: 'Refazer a ultima alteracao.',
  },
  {
    id: 'editor-new-block',
    name: 'Novo bloco',
    keys: 'Enter',
    where: 'Editor',
    description: 'Criar um novo bloco logo abaixo.',
  },
  {
    id: 'editor-delete-block',
    name: 'Remover bloco vazio',
    keys: 'Backspace',
    where: 'Editor',
    description: 'Apagar bloco vazio e voltar para o anterior.',
  },
  {
    id: 'tasks-nav',
    name: 'Navegar tarefas',
    keys: 'Seta Cima / Seta Baixo',
    where: 'Painel',
    description: 'Mover entre tarefas.',
  },
  {
    id: 'tasks-toggle',
    name: 'Concluir tarefa',
    keys: 'Espaco',
    where: 'Painel',
    description: 'Marcar/desmarcar a tarefa selecionada.',
  },
  {
    id: 'tasks-open',
    name: 'Abrir nota da tarefa',
    keys: 'Enter',
    where: 'Painel',
    description: 'Abrir a nota com a tarefa selecionada.',
  },
  {
    id: 'tasks-due',
    name: 'Definir vencimento rapido',
    keys: 'D',
    where: 'Painel',
    description: 'Abrir dialogo de vencimento.',
  },
  {
    id: 'tasks-snooze',
    name: 'Agendar 1 dia',
    keys: 'S',
    where: 'Painel',
    description: 'Agendar tarefa para amanha.',
  },
  {
    id: 'tasks-next-action',
    name: 'Marcar Next Action',
    keys: 'X',
    where: 'Painel',
    description: 'Alternar o status de Next Action.',
  },
  {
    id: 'tasks-priority',
    name: 'Alternar prioridade',
    keys: 'P',
    where: 'Painel',
    description: 'Ciclar entre P1, P2, P3 e sem prioridade.',
  },
  {
    id: 'tasks-status',
    name: 'Alternar status',
    keys: 'T',
    where: 'Painel',
    description: 'Ciclar entre aberta, em andamento e aguardando.',
  },
  {
    id: 'focus-complete',
    name: 'Concluir tarefa em foco',
    keys: 'Espaco',
    where: 'Agora',
    description: 'Marcar a tarefa atual como concluida.',
  },
  {
    id: 'focus-start',
    name: 'Iniciar/pausar foco',
    keys: 'Enter',
    where: 'Agora',
    description: 'Alternar a tarefa entre aberta e em andamento.',
  },
  {
    id: 'focus-nav',
    name: 'Navegar fila',
    keys: 'J / K',
    where: 'Agora',
    description: 'Ir para a proxima/anterior na fila.',
  },
  {
    id: 'focus-schedule',
    name: 'Agendar rapido',
    keys: 'S',
    where: 'Agora',
    description: 'Agendar para amanha.',
  },
  {
    id: 'focus-due',
    name: 'Prazo hoje',
    keys: 'D',
    where: 'Agora',
    description: 'Definir prazo para hoje.',
  },
  {
    id: 'focus-note',
    name: 'Nota rapida',
    keys: 'N',
    where: 'Agora',
    description: 'Criar uma nota rapida na tarefa em foco.',
  },
  {
    id: 'focus-set',
    name: 'Definir foco',
    keys: 'F',
    where: 'Agora',
    description: 'Definir foco pela primeira sugestao.',
  },
];
